---
abstract: 'helps track execution context in async programs'
author:
  - 'Ruslan Zakirov <Ruslan.Zakirov@gmail.com>'
build_requires:
  AnyEvent: 0
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Async::ContextSwitcher
name: Async-ContextSwitcher
no_index:
  directory:
    - inc
    - t
requires:
  Exporter::Tiny: 0
  perl: 5.10.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
